# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-11-04T05:12:33+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field

# Model Alert {  }

class Alerts(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    interlock_name: str = Field(..., title='Interlock Name')
    interlock_type: str = Field(..., title='Interlock Type')
    status: str = Field(..., title='Status')
    outlet_name: Optional[str] = Field(..., title='Outlet Name')
    state_name: Optional[str] = Field(..., title='State Name')
    region_name: Optional[str] = Field(..., title='Region Name')
    territory_name: Optional[str] = Field(..., title='Territory Name')
    sales_office_name: Optional[str] = Field(..., title='Sales Office Name')
    severity: str = Field(..., title='Severity')
    event_data: Optional[Dict[str, Any]] = Field(None, title='Event Data')
    alert_key: str = Field(..., title='Alert Key')
    acknowledged_by: Optional[str] = Field(..., title='Acknowledged By')
    cleared_by: Optional[str] = Field(..., title='Cleared By')
    notes: Optional[str] = Field(..., title='Notes')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class Attendents(BaseModel):
    id: int = Field(..., title='Id')
    first_name: str = Field(..., title='First Name')
    last_name: str = Field(..., title='Last Name')
    roid: int = Field(..., title='Roid')
    email: Optional[str] = Field(None, title='Email')
    address: Optional[Dict[str, Any]] = Field(None, title='Address')
    gender: Optional[str] = Field(None, title='Gender')
    proof: Optional[str] = Field(None, title='Proof')
    phone_number: Optional[str] = Field(None, title='Phone Number')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class AuditLog(BaseModel):
    id: int = Field(..., title='Id')
    user_id: Optional[int] = Field(None, title='User Id')
    user_name: str = Field(..., title='User Name')
    action: str = Field(..., title='Action')
    record_id: Optional[int] = Field(None, title='Record Id')
    status: Optional[str] = Field('success', title='Status')
    details: Optional[Dict[str, Any]] = Field(None, title='Details')
    description: str = Field(..., title='Description')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class BodyImportExcelApiFuelChartImportExcelPost(BaseModel):
    file: bytes = Field(..., title='File')


class DealerDensityUpdate(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    unit_name: Optional[str] = Field(..., title='Unit Name')
    products: List[Dict[str, Any]] = Field(..., title='Products')
    status: Optional[str] = Field('pending', title='Status')
    remote_response: Optional[List[Dict[str, Any]]] = Field(
        None, title='Remote Response'
    )
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class DispensingUnits(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    unit_name: Optional[str] = Field(None, title='Unit Name')
    thingsboard_device_id: Optional[str] = Field(None, title='Thingsboard Device Id')
    thingsboard_access_token: Optional[str] = Field(
        None, title='Thingsboard Access Token'
    )
    hardware_id: Optional[str] = Field(..., title='Hardware Id')
    mqtt_host: Optional[str] = Field(None, title='Mqtt Host')
    mqtt_port: Optional[int] = Field(None, title='Mqtt Port')
    manufacturer: Optional[str] = Field(None, title='Manufacturer')
    model: Optional[str] = Field(None, title='Model')
    serial_number: Optional[str] = Field(None, title='Serial Number')
    is_active: Optional[bool] = Field(True, title='Is Active')
    device_version: Optional[str] = Field(None, title='Device Version')
    status: Optional[str] = Field(None, title='Status')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class FuelChart(BaseModel):
    id: int = Field(..., title='Id')
    ro_id: int = Field(..., title='Ro Id')
    pump_numbers: List[int] = Field(..., title='Pump Numbers')
    dip: int = Field(..., title='Dip')
    volume: Optional[float] = Field(None, title='Volume')
    diff: Optional[float] = Field(None, title='Diff')
    capacity: Optional[float] = Field(None, title='Capacity')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class FuelTypes(BaseModel):
    id: int = Field(..., title='Id')
    name: str = Field(..., title='Name')
    code: Optional[str] = Field(None, title='Code')
    description: Optional[str] = Field(None, title='Description')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class Interlocks(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    tank_id: int = Field(..., title='Tank Id')
    interlock_message: str = Field(..., title='Interlock Message')
    interlock_type: str = Field(..., title='Interlock Type')
    nozzles: List[int] = Field(..., title='Nozzles')
    du_id: Optional[List[int]] = Field(..., title='Du Id')
    status: str = Field(..., title='Status')
    severity: str = Field(..., title='Severity')
    remote_response: Optional[Dict[str, Any]] = Field(None, title='Remote Response')
    fuel_dip_level: Optional[float] = Field(..., title='Fuel Dip Level')
    water_dip_level: Optional[float] = Field(..., title='Water Dip Level')
    locked_at: Optional[datetime] = Field(..., title='Locked At')
    unlocked_at: Optional[datetime] = Field(..., title='Unlocked At')
    duration_seconds: Optional[int] = Field(..., title='Duration Seconds')
    du_config: Optional[Dict[str, Any]] = Field(None, title='Du Config')
    outlet_name: Optional[str] = Field(..., title='Outlet Name')
    state_name: Optional[str] = Field(..., title='State Name')
    region_name: Optional[str] = Field(..., title='Region Name')
    territory_name: Optional[str] = Field(..., title='Territory Name')
    sales_office_name: Optional[str] = Field(..., title='Sales Office Name')
    acknowledged_by: Optional[str] = Field(..., title='Acknowledged By')
    cleared_by: Optional[str] = Field(..., title='Cleared By')
    notes: Optional[str] = Field(..., title='Notes')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class Nozzles(BaseModel):
    id: int = Field(..., title='Id')
    pump_id: int = Field(..., title='Pump Id')
    tank_id: int = Field(..., title='Tank Id')
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    pos_pump_id: int = Field(..., title='Pos Pump Id')
    tank_number: int = Field(..., title='Tank Number')
    nozzle_number: int = Field(..., title='Nozzle Number')
    pos_nozzle_id: int = Field(..., title='Pos Nozzle Id')
    nozzle_name: Optional[str] = Field(None, title='Nozzle Name')
    is_active: Optional[bool] = Field(True, title='Is Active')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class OnboardDevice(BaseModel):
    hardware_id: str = Field(..., title='Hardware Id')
    roid: int = Field(..., title='Roid')
    device_type: str = Field(..., title='Device Type')
    decive_id: List[int] = Field(..., title='Decive Id')


# class OnboardDispensor(BaseModel):
#     dispensing_units: List[DispensingUnits] = Field(..., title='Dispensing Units')
#     roid: int = Field(..., title='Roid')


# class OnboardNozzle(BaseModel):
#     nozzles: List[Nozzles] = Field(..., title='Nozzles')
#     roid: int = Field(..., title='Roid')


class PresetUpdateRequest(BaseModel):
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    pump: str = Field(..., title='Pump')
    nozzle_id: int = Field(..., title='Nozzle Id')
    preset_type: int = Field(..., title='Preset Type')
    # preset_value: Union[float, str] = Field(..., title='Preset Value')
    status: Optional[str] = Field('pending', title='Status')
    device_id: str = Field(..., title='Device Id')
    actions: Dict[str, Any] = Field(..., title='Actions')


class PriceUpdateHistory(BaseModel):
    id: int = Field(..., title='Id')
    du_id: int = Field(..., title='Du Id')
    roid: int = Field(..., title='Roid')
    fuel_type_id: int = Field(..., title='Fuel Type Id')
    fuel_type_name: str = Field(..., title='Fuel Type Name')
    price: float = Field(..., title='Price')
    price_date: Optional[int] = Field(None, title='Price Date')
    attempts: Optional[int] = Field(0, title='Attempts')
    success_count: Optional[int] = Field(0, title='Success Count')
    fail_count: Optional[int] = Field(0, title='Fail Count')
    last_status: Optional[str] = Field('PENDING', title='Last Status')
    last_attempt: Optional[datetime] = Field(None, title='Last Attempt')
    last_ack_timestamp: Optional[datetime] = Field(None, title='Last Ack Timestamp')
    first_attempt_timestamp: Optional[datetime] = Field(
        None, title='First Attempt Timestamp'
    )
    notes: Optional[str] = Field(None, title='Notes')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


# class ProductDensity(BaseModel):
#     fuel_type: Optional[str] = Field(None, title='Fuel Type')
#     density: Union[float, str] = Field(..., title='Density')


class Pumps(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    pos_pump_id: int = Field(..., title='Pos Pump Id')
    pump_identifier: str = Field(..., title='Pump Identifier')
    pump_name: Optional[str] = Field(None, title='Pump Name')
    is_active: Optional[bool] = Field(True, title='Is Active')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class RODailyPrice(BaseModel):
    id: int = Field(..., title='Id')
    ro_id: int = Field(..., title='Ro Id')
    roid: int = Field(..., title='Roid')
    fuel_type_id: int = Field(..., title='Fuel Type Id')
    fuel_type: str = Field(..., title='Fuel Type')
    price: float = Field(..., title='Price')
    price_date: Optional[int] = Field(None, title='Price Date')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


# class RSP(BaseModel):
#     fuel_type: Optional[str] = Field(None, title='Fuel Type')
#     Price: Union[float, str] = Field(..., title='Price')


class RSPUpdate(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    unit_name: Optional[str] = Field(..., title='Unit Name')
    products: List[Dict[str, Any]] = Field(..., title='Products')
    status: Optional[str] = Field('pending', title='Status')
    remote_response: Optional[List[Dict[str, Any]]] = Field(
        None, title='Remote Response'
    )
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


# class RSPUpdateRequest(BaseModel):
#     roid: int = Field(..., title='Roid')
#     du_id: int = Field(..., title='Du Id')
#     products: List[RSP] = Field(..., title='Products')
#     status: Optional[str] = Field('pending', title='Status')
#     device_id: str = Field(..., title='Device Id')
#     actions: Dict[str, Any] = Field(..., title='Actions')


class Regions(BaseModel):
    id: int = Field(..., title='Id')
    name: str = Field(..., title='Name')
    code: Optional[str] = Field(None, title='Code')
    updated: Optional[datetime] = Field(None, title='Updated')
    created: Optional[datetime] = Field(None, title='Created')


class RetailOutlets(BaseModel):
    id: int = Field(..., title='Id')
    outlet_name: str = Field(..., title='Outlet Name')
    roid: Optional[int] = Field(None, title='Roid')
    region_id: int = Field(..., title='Region Id')
    state_id: int = Field(..., title='State Id')
    territory_id: int = Field(..., title='Territory Id')
    sales_office_id: int = Field(..., title='Sales Office Id')
    region_name: str = Field(..., title='Region Name')
    state_name: str = Field(..., title='State Name')
    territory_name: str = Field(..., title='Territory Name')
    sales_office_name: str = Field(..., title='Sales Office Name')
    contact_person: Optional[str] = Field(None, title='Contact Person')
    phone: Optional[str] = Field(None, title='Phone')
    city: Optional[str] = Field(None, title='City')
    email: Optional[str] = Field(None, title='Email')
    address: Optional[str] = Field(None, title='Address')
    is_active: Optional[bool] = Field(True, title='Is Active')
    onboarding_date: Optional[datetime] = Field(None, title='Onboarding Date')
    outlet_type: Optional[str] = Field('petrol_pump', title='Outlet Type')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')
    ro_atg_vendor: Optional[str] = Field(None, title='Ro Atg Vendor')
    rosi_vendor: Optional[str] = Field(None, title='Rosi Vendor')
    automation_vendor: Optional[str] = Field(None, title='Automation Vendor')
    fcc_update_date: Optional[str] = Field(None, title='Fcc Update Date')
    automation_engineer: Optional[str] = Field(None, title='Automation Engineer')
    sdwan_vendor: Optional[str] = Field(None, title='Sdwan Vendor')
    vsat_vendor: Optional[str] = Field(None, title='Vsat Vendor')
    vsat_installation_date: Optional[datetime] = Field(
        None, title='Vsat Installation Date'
    )
    vsat_integration_date: Optional[datetime] = Field(
        None, title='Vsat Integration Date'
    )
    itps_vendor1: Optional[str] = Field(None, title='Itps Vendor1')
    itps_vendor2: Optional[str] = Field(None, title='Itps Vendor2')


class Roles(BaseModel):
    id: int = Field(..., title='Id')
    role: str = Field(..., title='Role')
    role_id: Optional[str] = Field(..., title='Role Id')
    is_system_role: Optional[bool] = Field(False, title='Is System Role')
    role_type: Optional[str] = Field('internal', title='Role Type')
    description: Optional[str] = Field(None, title='Description')
    categories: Optional[List[str]] = Field(None, title='Categories')
    operations: Optional[List[str]] = Field(None, title='Operations')
    permissions: Optional[List[str]] = Field(None, title='Permissions')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class SalesOffices(BaseModel):
    id: int = Field(..., title='Id')
    territory_id: int = Field(..., title='Territory Id')
    name: str = Field(..., title='Name')
    code: Optional[str] = Field(None, title='Code')
    updated: Optional[datetime] = Field(None, title='Updated')
    created: Optional[datetime] = Field(None, title='Created')


class SendDUMessage(BaseModel):
    action_type: str = Field(..., title='Action Type')
    roid: int = Field(..., title='Roid')
    device_id: str = Field(..., title='Device Id')
    action: Dict[str, Any] = Field(..., title='Action')


class Shifts(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    shift_name: str = Field(..., title='Shift Name')
    shift_start_time: datetime = Field(..., title='Shift Start Time')
    shift_end_time: datetime = Field(..., title='Shift End Time')
    staff: List[Dict[str, Any]] = Field(..., title='Staff')
    shift_status: Optional[str] = Field('open', title='Shift Status')
    status: Optional[str] = Field('active', title='Status')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class States(BaseModel):
    id: int = Field(..., title='Id')
    region_id: int = Field(..., title='Region Id')
    name: str = Field(..., title='Name')
    code: Optional[str] = Field(None, title='Code')
    updated: Optional[datetime] = Field(None, title='Updated')
    created: Optional[datetime] = Field(None, title='Created')


# class TTReceipt(BaseModel):
#     id: int = Field(..., title='Id')
#     tt_number: str = Field(..., title='Tt Number')
#     invoice_number: str = Field(..., title='Invoice Number')
#     invoice_date: datetime = Field(..., title='Invoice Date')
#     roid: int = Field(..., title='Roid')
#     tank_id: int = Field(..., title='Tank Id')
#     supply_point: Optional[str] = Field(..., title='Supply Point')
#     decant_start_time: datetime = Field(..., title='Decant Start Time')
#     decant_end_time: datetime = Field(..., title='Decant End Time')
#     no_of_chambers: Optional[int] = Field(None, title='No Of Chambers')
#     prod_chamber1: Optional[str] = Field(None, title='Prod Chamber1')
#     qty_chamber1: Optional[Union[float, str]] = Field(None, title='Qty Chamber1')
#     decanted_volume1: Optional[float] = Field(None, title='Decanted Volume1')
#     prod_chamber2: Optional[str] = Field(None, title='Prod Chamber2')
#     qty_chamber2: Optional[Union[float, str]] = Field(None, title='Qty Chamber2')
#     decanted_volume2: Optional[float] = Field(None, title='Decanted Volume2')
#     prod_chamber3: Optional[str] = Field(None, title='Prod Chamber3')
#     qty_chamber3: Optional[Union[float, str]] = Field(None, title='Qty Chamber3')
#     decanted_volume3: Optional[float] = Field(None, title='Decanted Volume3')
#     prod_chamber4: Optional[str] = Field(None, title='Prod Chamber4')
#     qty_chamber4: Optional[Union[float, str]] = Field(None, title='Qty Chamber4')
#     decanted_volume4: Optional[float] = Field(None, title='Decanted Volume4')
#     prod_chamber5: Optional[str] = Field(None, title='Prod Chamber5')
#     qty_chamber5: Optional[Union[float, str]] = Field(None, title='Qty Chamber5')
#     decanted_volume5: Optional[float] = Field(None, title='Decanted Volume5')
#     prod_chamber6: Optional[str] = Field(None, title='Prod Chamber6')
#     qty_chamber6: Optional[Union[float, str]] = Field(None, title='Qty Chamber6')
#     decanted_volume6: Optional[float] = Field(None, title='Decanted Volume6')
#     chamber_id: Optional[str] = Field(..., title='Chamber Id')
#     before_level_mm: Union[float, str] = Field(..., title='Before Level Mm')
#     before_volume_liters: Union[float, str] = Field(..., title='Before Volume Liters')
#     before_density_kg_m3: Optional[Union[float, str]] = Field(
#         ..., title='Before Density Kg M3'
#     )
#     before_temperature_celsius: Optional[Union[float, str]] = Field(
#         ..., title='Before Temperature Celsius'
#     )
#     after_level_mm: Union[float, str] = Field(..., title='After Level Mm')
#     after_volume_liters: Union[float, str] = Field(..., title='After Volume Liters')
#     after_density_kg_m3: Optional[Union[float, str]] = Field(
#         ..., title='After Density Kg M3'
#     )
#     after_temperature_celsius: Optional[Union[float, str]] = Field(
#         ..., title='After Temperature Celsius'
#     )
#     net_quantity_receipt: Union[float, str] = Field(..., title='Net Quantity Receipt')
#     net_quantity_decanted: Union[float, str] = Field(..., title='Net Quantity Decanted')
#     net_sale_during_decantation: Optional[Union[float, str]] = Field(
#         ..., title='Net Sale During Decantation'
#     )
#     shortage: Optional[Union[float, str]] = Field(..., title='Shortage')
#     fuel_type: Optional[str] = Field(..., title='Fuel Type')
#     created: Optional[datetime] = Field(None, title='Created')
#     updated: Optional[datetime] = Field(None, title='Updated')
#     created_by: Optional[int] = Field(..., title='Created By')
#     updated_by: Optional[int] = Field(..., title='Updated By')


class TankInventory(BaseModel):
    id: int = Field(..., title='Id')
    device_id: str = Field(..., title='Device Id')
    roid: int = Field(..., title='Roid')
    product_id: int = Field(..., title='Product Id')
    probe_number: int = Field(..., title='Probe Number')
    level_status: str = Field(..., title='Level Status')
    probe_status: str = Field(..., title='Probe Status')
    water_level: Union[float, str] = Field(..., title='Water Level')
    fuel_level: Union[float, str] = Field(..., title='Fuel Level')
    water_level_mm: Optional[Union[float, str]] = Field(None, title='Water Level Mm')
    fuel_level_mm: Optional[Union[float, str]] = Field(None, title='Fuel Level Mm')
    density: Union[float, str] = Field(..., title='Density')
    temperature: Optional[Union[float, str]] = Field(None, title='Temperature')
    outlet_name: Optional[str] = Field(..., title='Outlet Name')
    state_name: Optional[str] = Field(..., title='State Name')
    region_name: Optional[str] = Field(..., title='Region Name')
    territory_name: Optional[str] = Field(..., title='Territory Name')
    sales_office_name: Optional[str] = Field(..., title='Sales Office Name')
    reading_time: datetime = Field(..., title='Reading Time')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class TankInventoryData(BaseModel):
    inventory: List[TankInventory] = Field(..., title='Inventory')
    roid: int = Field(..., title='Roid')


class Tanks(BaseModel):
    id: int = Field(..., title='Id')
    roid: int = Field(..., title='Roid')
    tank_number: int = Field(..., title='Tank Number')
    probe_serial_number: Optional[str] = Field(..., title='Probe Serial Number')
    tank_name: Optional[str] = Field(None, title='Tank Name')
    thingsboard_device_id: Optional[str] = Field(None, title='Thingsboard Device Id')
    thingsboard_access_token: Optional[str] = Field(
        None, title='Thingsboard Access Token'
    )
    hardware_id: Optional[str] = Field(..., title='Hardware Id')
    mqtt_host: Optional[str] = Field(None, title='Mqtt Host')
    mqtt_port: Optional[int] = Field(None, title='Mqtt Port')
    probe_make: Optional[str] = Field(None, title='Probe Make')
    probe_model: Optional[str] = Field(None, title='Probe Model')
    device_version: Optional[str] = Field(None, title='Device Version')
    status: Optional[str] = Field(None, title='Status')
    fuel_type_id: int = Field(..., title='Fuel Type Id')
    capacity: Optional[float] = Field(None, title='Capacity')
    height_mm: Optional[float] = Field(None, title='Height Mm')
    is_active: Optional[bool] = Field(True, title='Is Active')
    unit_of_measure: Optional[str] = Field(None, title='Unit Of Measure')
    minimum_level: Optional[float] = Field(None, title='Minimum Level')
    atg_comm_failure_flag: Optional[str] = Field(None, title='Atg Comm Failure Flag')
    atg_comm_failure_value: Optional[str] = Field(None, title='Atg Comm Failure Value')
    tt_receipt_lock_flag: Optional[str] = Field(None, title='Tt Receipt Lock Flag')
    tt_receipt_lock_interval: Optional[str] = Field(
        None, title='Tt Receipt Lock Interval'
    )
    tt_decantation_flag: Optional[str] = Field(None, title='Tt Decantation Flag')
    water_level_high_flag: Optional[str] = Field(None, title='Water Level High Flag')
    water_level_high_value: Optional[str] = Field(None, title='Water Level High Value')
    low_product_flag: Optional[str] = Field(None, title='Low Product Flag')
    low_product_value: Optional[str] = Field(None, title='Low Product Value')
    tank_status: Optional[str] = Field(None, title='Tank Status')
    cs_id: Optional[str] = Field(None, title='Cs Id')
    update_flag: Optional[str] = Field(None, title='Update Flag')
    date_updated_str: Optional[str] = Field(None, title='Date Updated Str')
    xfr_datetime: Optional[str] = Field(None, title='Xfr Datetime')
    last_available_stock_date: Optional[str] = Field(
        None, title='Last Available Stock Date'
    )
    last_available_stock_product: Optional[str] = Field(
        None, title='Last Available Stock Product'
    )
    last_available_stock_quantity: Optional[float] = Field(
        None, title='Last Available Stock Quantity'
    )
    last_available_stock_density15: Optional[float] = Field(
        None, title='Last Available Stock Density15'
    )
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class Territories(BaseModel):
    id: int = Field(..., title='Id')
    state_id: int = Field(..., title='State Id')
    name: str = Field(..., title='Name')
    code: Optional[str] = Field(None, title='Code')
    updated: Optional[datetime] = Field(None, title='Updated')
    created: Optional[datetime] = Field(None, title='Created')


class Transactions(BaseModel):
    id: int = Field(..., title='Id')
    transaction_id: str = Field(..., title='Transaction Id')
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    pump_num: int = Field(..., title='Pump Num')
    nozz_num: int = Field(..., title='Nozz Num')
    tank_num: int = Field(..., title='Tank Num')
    fuel_type: Optional[str] = Field(..., title='Fuel Type')
    test_transaction: Optional[bool] = Field(False, title='Test Transaction')
    unit_price: Union[float, str] = Field(..., title='Unit Price')
    dispensed_amount: Union[float, str] = Field(..., title='Dispensed Amount')
    dispensed_volume: Union[float, str] = Field(..., title='Dispensed Volume')
    start_amount_totalizer: Union[float, str] = Field(
        ..., title='Start Amount Totalizer'
    )
    start_volume_totalizer: Union[float, str] = Field(
        ..., title='Start Volume Totalizer'
    )
    end_amount_totalizer: Union[float, str] = Field(..., title='End Amount Totalizer')
    end_volume_totalizer: Union[float, str] = Field(..., title='End Volume Totalizer')
    outlet_name: Optional[str] = Field(..., title='Outlet Name')
    state_name: Optional[str] = Field(..., title='State Name')
    region_name: Optional[str] = Field(..., title='Region Name')
    territory_name: Optional[str] = Field(..., title='Territory Name')
    sales_office_name: Optional[str] = Field(..., title='Sales Office Name')
    start_time: datetime = Field(..., title='Start Time')
    end_time: datetime = Field(..., title='End Time')
    preset_type: Optional[str] = Field(None, title='Preset Type')
    preset_amount: Optional[Union[float, str]] = Field(None, title='Preset Amount')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')


class TransactionsData(BaseModel):
    transactions: List[Transactions] = Field(..., title='Transactions')
    roid: int = Field(..., title='Roid')


class Users(BaseModel):
    id: int = Field(..., title='Id')
    first_name: str = Field(..., title='First Name')
    last_name: str = Field(..., title='Last Name')
    email: str = Field(..., title='Email')
    role: Optional[str] = Field(..., title='Role')
    is_verified: bool = Field(..., title='Is Verified')
    keycloak_id: Optional[str] = Field(..., title='Keycloak Id')
    user_type: Optional[str] = Field('internal', title='User Type')
    region_name: str = Field(..., title='Region Name')
    state_name: str = Field(..., title='State Name')
    territory_name: str = Field(..., title='Territory Name')
    sales_office_name: str = Field(..., title='Sales Office Name')
    created: Optional[datetime] = Field(None, title='Created')
    updated: Optional[datetime] = Field(None, title='Updated')
    custom_fields: Optional[Dict[str, Any]] = Field(None, title='Custom Fields')


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class DensityUpdateRequest(BaseModel):
    roid: int = Field(..., title='Roid')
    du_id: int = Field(..., title='Du Id')
    products: List[ProductDensity] = Field(..., title='Products')
    status: Optional[str] = Field('pending', title='Status')
    device_id: str = Field(..., title='Device Id')
    actions: Dict[str, Any] = Field(..., title='Actions')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')


class OnboardPumps(BaseModel):
    pumps: List[Pumps] = Field(..., title='Pumps')
    roid: int = Field(..., title='Roid')


class OnboardTanks(BaseModel):
    tanks: List[Tanks] = Field(..., title='Tanks')
    roid: int = Field(..., title='Roid')



"""First i have downloaded the openapi.json file and then
I have pip install datamodel-codegen 
and run the below command with input, input file type and output path 
datamodel-codegen --input C:\Users\Rakesh\Desktop\openapi.json --input-file-type openapi --output C:\Users\Rakesh\Desktop\models.py
#>>> What is datamodel-code-generator?
datamodel-code-generator is an open-source Python tool that automatically generates Pydantic models, dataclasses, or TypedDicts from structured data sources like:
>OpenAPI / Swagger (JSON or YAML)
>JSON Schema
>JSON / YAML samples
>CSV files
>GraphQL schemas
>SQLAlchemy models
>Proto files
"""